image: artorp/docker-java8-maven-testfxmonocle:1.2
# image: krissrex/docker-java8-maven-testfxmonocle:1.0
# image: kaiwinter/docker-java8-maven
# image: maven:3.3.9-jdk-8

# most of this taken from https://stackoverflow.com/questions/37785154/how-to-enable-maven-artifact-caching-for-gitlab-ci-runner

cache:
  paths:
    - .m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Dgitlab-ci=true"

build-job:
  stage: build
  script:
    - "mvn clean compile -f tdt4140-gr1811/pom.xml $MAVEN_CLI_OPTS"

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn package -f tdt4140-gr1811/pom.xml $MAVEN_CLI_OPTS"
    - "python3.5 python_scripts/jacoco_printer.py tdt4140-gr1811/app.core/target/site/jacoco/index.html"
    - "mv tdt4140-gr1811/app.core/target core_target"
  artifacts:
    when: always
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 6 mos 1 day
    paths:
      - core_target

integrationtest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn verify -f tdt4140-gr1811/pom.xml $MAVEN_CLI_OPTS -DskipUTs=true"
  services:
  - name: mysql:latest
    alias: mysql-it
  variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE: IntegrationTest
    MYSQL_ROOT_PASSWORD: abcd

